# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HckTheSystem' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HckTheSystem
  pod 'Alamofire', '~> 4.7'
  pod 'FaveButton', '~> 2.0.3'
  pod 'Socket.IO-Client-Swift', '~> 11.1.3'
end
